version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "08:00"
    commit-message:
      prefix: "build(actions)"
      include: "scope"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "build(python)"
      include: "scope"
