# https://pre-commit.com/#pre-commit-configyaml---top-level
default_stages:
  - commit

default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

exclude: pypoetry

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        description: Security oriented static analyser for python code
        exclude: ^tests/

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.10
    hooks:
      - id: vulture
        description: Find dead Python code
        entry: vulture
        args:
          [
            "--min-confidence",
            "90",
            "--exclude",
            "*env*",
            "python_package_publish",
          ]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell reviews
        language: python
        types: [text]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        args: ["--ignore-missing-imports", "--scripts-are-modules"]
        require_serial: true
        additional_dependencies: [types-click==7.1.2, types-freezegun==0.1.4]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.1
    hooks:
      - id: commitizen
        stages:
          - commit-msg
      - id: commitizen-branch
        stages:
          - push
        args:
          - --rev-range
          - origin/main..HEAD
        always_run: true
        pass_filenames: false
